const enTranslations = {
  home: {
    register: 'Register',
    login: 'Login',
    tandc: 'Terms & conditions',
  },
  login: {
    enterMobileNumber: 'Enter your mobile number:',
    letsBegin: "Let's Begin",
    phoneNumber: 'Phone number',
    modalTitle_1: 'We apologize',
    FirstModalmessage: "We didn't find the mobile number registered",
    FirstModalmessage2: 'Change mobile number',
    modalTitle_2: 'Hi 👋',
    secondModalMessage: '¡Please enter a phone number!',
  },
  codeOtp: {
    enterVerificationCode: 'Enter your verification code',
    codeSent: 'A 4 digit code has been sent to your phone',
    verifyAndProceed: 'Verify & Proceed',
    didntReceiveCode: "Didn't you receive the code?",
    sendAgain: 'Send again',
    title: 'Sorry',
    message: 'The code you entered is incorrect',
    code: 'Try again',
    message2Modal: 'Please enter the code.',
  },
  restaurants: {
    addRestaurant: 'Contact us to add a restaurant!',
  },
  suppliers: {
    addSuppliers: 'Contact us to add suppliers!',
  },
  menuPrimary: {
    Settings: 'Settings',
    orders: 'Orders',
    records: 'Records',
    chat: 'Chat',
    titleSettings: 'Settings',
  },
  stackNavigator: {
    chooseYourRestaurant: 'Choose your restaurant',
    suppliers: 'Suppliers',
    makeYourOrder: 'Make your order',
    orderDetail: 'Order detail',
  },

  productSearcher: {
    placeholder: 'Search for products',
  },
  favorites: {
    findFirstPart: 'You have ',
    findSecondPart: ' favorites products:',
  },
  categoriesMenu: {
    favorites: 'Favorites',
    continue: 'Continue',
  },
  orderDetails: {
    paymentDetails: 'Payment details',
    net: 'Net',
    tax: 'Tax',
    currentvalue: 'Current value',
    continue: 'Continue',
  },
  deliveryDetail: {
    address: 'Address',
    deliver: 'Deliver',
    specialRequirements: 'Any special requirements?',
    continue: 'Continue',
  },
  orderSuccessful: {
    successful: 'Successful!',
    yourOrderSuccessful: 'Your order is successful',
    yourOrders: 'Your orders',
    downloadPDF: 'Download PDF',
  },
  record: {
    searchPlaceholder: 'Search for products',
    pastOrders: 'Past orders',
    pendingOrders: 'Pending orders',
    viewDetails: 'View details',
    order: '#Order',
    amount: 'Amount',
    date: 'Date',
    noOrders: 'No orders yet',
    bttnNoOrders: 'Order now',
    noOrdersDate: 'No orders on this date',
  },
  disputeRecord: {
    enterQuantityDelivered: 'Enter quantity delivered:',
    addComment: 'Add a comment:',
    sendNextOrder: 'Send Next Order',
    creditNote: 'Credit note',
    wrongQuantity: 'Wrong quantity',
    defective: 'Defective',
    other: 'Other',
    leaveYourCommentsHere: 'Leave your comments here:',
    send: 'Send',
  },
  uploadFile: {
    attachPhoto: 'Attach photo:',
    customUpload: 'Custom Upload',
  },
  pendingRecord: {
    products: 'Products',
    reception: 'Reception',
    supplierDetails: 'Supplier details',
    productDetails: 'Product details',
    paymentDetails: 'Payment details',
    tax: 'Tax',
    currentTotal: 'Current value',
    checkYourProducts: 'Check your products',
    openDispute: 'Open dispute',
    confirmOrder: 'Confirm order',
  },
  stackRecord: {
    yourOrders: 'Your orders',
    orderDetails: 'Order details',
    whatWentWrong: 'What went wrong?',
  },
  settings: {
    title: 'Settings',
    hi: 'Hi',
    helpText: 'How can we help you?',
    restaurants: 'Restaurants',
    editRestaurants: 'Edit your restaurants',
    suppliers: 'Suppliers',
    editSuppliers: 'Edit your suppliers',
    languages: 'Languages',
    english: 'English',
    spanish: 'Spanish',
    portuguese: 'Portuguese',
    faq: 'FAQ',
    termsAndConditions: 'Terms & conditions',
    logOut: 'Log out',
  },
  pastRecord: {
    supplierDetails: 'Supplier details',
    productDetails: 'Product details',
    paymentDetails: 'Payment details',
    tax: 'Tax',
    currentTotal: 'Current value',
  },
  productFind: {
    youHave: 'You have',
    foundProducts: 'found products:',
  },
  deleteProduct: {
    deleteProduct: 'Delete product',
    areYouSureToDelete: 'Are you sure to delete',
    cancel: 'Cancel',
    delete: 'Delete',
  },
  settingsFaq: {
    tittle1: 'How can ',
    tittle2: 'we help you?',
    question1: 'How do I add another restaurant?',
    question2: 'How do I add a supplier?',
    question3: 'What is Grownet?',
    question4: 'Where do I view my current orders?',
    question5: 'A received order is incomplete. What should I do?',
    answer1:
      'Contact us through our chat and let us know the name of the restaurant you want to add.',
    answer2:
      'Get in touch via our chat to add the supplier you need. Remember, we have the best suppliers for vegetables, fruits, beverages, meats, and much more.',
    answer3:
      "Discover Grownet: Your restaurant's supply solution. We make sourcing supplies a breeze, connecting you with top London market providers for fresh, high-quality products at great prices. Manage multiple restaurant locations, streamline your purchasing, and focus on what matters most – delivering a great dining experience. Join the supply management revolution with Grownet and elevate your restaurant business today!",
    answer4:
      "Go to the menu and access the 'Records' section. There, you'll find your current and previous orders. You can filter by date and view more details about all your products.",
    answer5:
      "Go to the menu and navigate to the 'Records' section. Search for the order under 'Current Orders'. You can filter by date or manually search for the order. Choose 'View details' and open a dispute for the incomplete product.",
  },
}

export default enTranslations
