const enTranslations = {
  home: {
    register: 'Register',
    login: 'Login',
    tandc: 'Terms & conditions',
  },
  login: {
    enterMobileNumber: 'Enter your mobile number:',
    letsBegin: "Let's Begin",
    phoneNumber: 'Phone number',
    modalTitle_1: 'We apologize',
    FirstModalmessage: "We didn't find the mobile number registered",
    FirstModalmessage2: 'Change mobile number',
    modalTitle_2: 'Hi 👋',
    secondModalMessage: '¡Please enter a phone number!',
  },
  codeOtp: {
    enterVerificationCode: 'Enter your verification code',
    codeSent: 'A 4 digit code has been sent to your phone',
    verifyAndProceed: 'Verify & Proceed',
    didntReceiveCode: "Didn't you receive the code?",
    sendAgain: 'Send again',
    title: 'Sorry',
    message: 'The code you entered is incorrect',
    code: 'Try again',
    message2Modal: 'Please enter the code.',
  },
  restaurants: {
    addRestaurant: 'Contact us to add a restaurant!',
  },
  suppliers: {
    addSuppliers: 'Contact us to add suppliers!',
  },
  menuPrimary: {
    Settings: 'Settings',
    orders: 'Orders',
    records: 'Records',
    chat: 'Chat',
    titleSettings: 'Settings',
  },
  stackNavigator: {
    chooseYourRestaurant: 'Choose your restaurant',
    suppliers: 'Suppliers',
    makeYourOrder: 'Make your order',
    orderDetail: 'Order detail',
  },

  productSearcher: {
    placeholder: 'Search for products',
  },
  favorites: {
    findFirstPart: 'You have ',
    findSecondPart: ' favorites products:',
  },
  categoriesMenu: {
    favorites: 'Favorites',
    continue: 'Continue',
  },
  orderDetails: {
    paymentDetails: 'Payment details',
    net: 'Net',
    tax: 'Tax',
    currentvalue: 'Current value',
    continue: 'Continue',
  },
  deliveryDetail: {
    address: 'Address',
    deliver: 'Deliver',
    specialRequirements: 'Any special requirements?',
    continue: 'Continue',
  },
  orderSuccessful: {
    successful: 'Successful!',
    yourOrderSuccessful: 'Your order is successful',
    yourOrders: 'Your orders',
    downloadPDF: 'Download PDF',
  },
  record: {
    searchPlaceholder: 'Search for products',
    pastOrders: 'Past orders',
    pendingOrders: 'Pending orders',
    viewDetails: 'View details',
    order: '#Order',
    amount: 'Amount',
    date: 'Date',
    noOrders: 'No orders yet',
    bttnNoOrders: 'Order now',
    noOrdersDate: 'No orders on this date',
  },
  disputeRecord: {
    enterQuantityDelivered: 'Enter quantity delivered:',
    addComment: 'Add a comment:',
    sendNextOrder: 'Send Next Order',
    creditNote: 'Credit note',
    wrongQuantity: 'Wrong quantity',
    defective: 'Defective',
    other: 'Other',
    leaveYourCommentsHere: 'Leave your comments here:',
    send: 'Send',
  },
  uploadFile: {
    attachPhoto: 'Attach photo:',
    customUpload: 'Custom Upload',
  },
  pendingRecord: {
    products: 'Products',
    reception: 'Reception',
    supplierDetails: 'Supplier details',
    productDetails: 'Product details',
    paymentDetails: 'Payment details',
    tax: 'Tax',
    currentTotal: 'Current value',
    checkYourProducts: 'Check your products',
    openDispute: 'Open dispute',
    confirmOrder: 'Confirm order',
  },
  stackRecord: {
    yourOrders: 'Your orders',
    orderDetails: 'Order details',
    whatWentWrong: 'What went wrong?',
  },
  settings: {
    title: 'Settings',
    hi: 'Hi',
    helpText: 'How can we help you?',
    restaurants: 'Restaurants',
    editRestaurants: 'Edit your restaurants',
    suppliers: 'Suppliers',
    editSuppliers: 'Edit your suppliers',
    languages: 'Languages',
    english: 'English',
    spanish: 'Spanish',
    portuguese: 'Portuguese',
    faq: 'FAQ',
    termsAndConditions: 'Terms & conditions',
    logOut: 'Log out',
  },
  pastRecord: {
    supplierDetails: 'Supplier details',
    productDetails: 'Product details',
    paymentDetails: 'Payment details',
    tax: 'Tax',
    currentTotal: 'Current value',
  },
  productFind: {
    youHave: 'You have',
    foundProducts: 'found products:',
  },
  deleteProduct: {
    deleteProduct: 'Delete product',
    areYouSureToDelete: 'Are you sure to delete',
    cancel: 'Cancel',
    delete: 'Delete',
  },
}

export default enTranslations
