const esTranslations = {
  home: {
    register: 'Registrarse',
    login: 'Iniciar sesión',
    tandc: 'Términos y condiciones',
  },
  login: {
    enterMobileNumber: 'Ingresa tu número de teléfono móvil:',
    letsBegin: 'Iniciar',
    phoneNumber: 'Número de teléfono',
    modalTitle_1: 'Pedimos disculpas',
    FirstModalmessage: 'No encontramos el número de móvil registrado',
    FirstModalmessage2: 'Cambiar número de móvil',
    modalTitle_2: '¡Hola 👋!',
    secondModalMessage: '¡Por favor ingresa un número de teléfono!',
  },
  codeOtp: {
    enterVerificationCode: 'Ingresa tu código de verificación',
    codeSent: 'Se ha enviado un código de 4 dígitos a tu teléfono',
    verifyAndProceed: 'Verificar y Continuar',
    didntReceiveCode: '¿No recibiste el código?',
    sendAgain: 'Enviar nuevamente',
  },
  restaurants: {
    addRestaurant: '¡Contáctanos para agregar restaurantes!',
  },
  suppliers: {
    addSuppliers: '¡Contáctanos para agregar proveedores!',
  },
  menuPrimary: {
    Settings: 'Ajustes',
    orders: 'Órdenes',
    records: 'Historial',
    chat: 'Chat',
    titleSettings: 'Configuración',
  },
  stackNavigator: {
    chooseYourRestaurant: 'Elige tu restaurante',
    suppliers: 'Proveedores',
    makeYourOrder: 'Realiza tu pedido',
    orderDetail: 'Detalle del pedido',
  },

  productSearcher: {
    placeholder: 'Buscar productos',
  },
  favorites: {
    findFirstPart: 'Usted tiene ',
    findSecondPart: ' favoritos encontrados:',
  },
  categoriesMenu: {
    favorites: 'Favoritos',
    continue: 'Continuar',
  },
  orderDetails: {
    paymentDetails: 'Detalles del pago',
    net: 'Neto',
    tax: 'Impuesto',
    currentvalue: 'Valor actual',
    continue: 'Continuar',
  },
  deliveryDetail: {
    address: 'Dirección',
    deliver: 'Entrega',
    specialRequirements: '¿Algún requisito especial?',
    continue: 'Continuar',
  },
  orderSuccessful: {
    successful: '¡Felicitaciones!',
    yourOrderSuccessful: 'Tu pedido se realizó con éxito',
    yourOrders: 'Tus pedidos',
    downloadPDF: 'Descargar PDF',
  },
  record: {
    searchPlaceholder: 'Buscar productos',
    pastOrders: 'Órdenes anteriores',
    pendingOrders: 'Órdenes pendientes',
    viewDetails: 'Ver detalles',
    order: '#Orden',
    amount: 'Monto',
    date: 'Fecha',
  },
  pendingRecord: {
    products: 'Productos',
    reception: 'Recepción',
    supplierDetails: 'Detalles del proveedor',
    productDetails: 'Detalles del producto',
    paymentDetails: 'Detalles del pago',
    tax: 'Impuesto',
    currentTotal: 'Valor actual',
    checkYourProducts: 'Verifica tus productos',
    openDispute: 'Abrir disputa',
    confirmOrder: 'Confirmar pedido',
  },
  stackRecord: {
    yourOrders: 'Tus pedidos',
    orderDetails: 'Detalles del pedido',
    whatWentWrong: '¿Qué salió mal?',
  },
  settings: {
    title: 'Configuración',
    hi: 'Hola',
    helpText: '¿Cómo podemos ayudarte?',
    restaurants: 'Restaurantes',
    editRestaurants: 'Editar tus restaurantes',
    suppliers: 'Proveedores',
    editSuppliers: 'Editar tus proveedores',
    languages: 'Idiomas',
    english: 'Inglés',
    spanish: 'Español',
    portuguese: 'Portugués',
    faq: 'Preguntas frecuentes',
    termsAndConditions: 'Términos y condiciones',
    logOut: 'Cerrar sesión',
  },
  pastRecord: {
    supplierDetails: 'Detalles del proveedor',
    productDetails: 'Detalles del producto',
    paymentDetails: 'Detalles del pago',
    tax: 'Impuesto',
    currentTotal: 'Valor actual',
  },
  productFind: {
    youHave: 'Tienes',
    foundProducts: 'productos encontrados:',
  },
  deleteProduct: {
    deleteProduct: 'Eliminar producto',
    areYouSureToDelete: '¿Estás seguro de eliminar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
  },
}

export default esTranslations
