const ptTranslations = {
  home: {
    register: 'Registrar-se',
    login: 'Entrar',
    tandc: 'Termos e condições',
  },
  login: {
    enterMobileNumber: 'Digite o número do seu celular:',
    letsBegin: 'Começar',
    phoneNumber: 'Número de telefone',
    modalTitle_1: 'Pedimos desculpas',
    FirstModalmessage: 'Não encontramos o número de celular registrado',
    FirstModalmessage2: 'Alterar número de celular',
    modalTitle_2: 'Oi 👋',
    secondModalMessage: 'Por favor, insira um número de telefone!',
  },
  codeOtp: {
    enterVerificationCode: 'Insira seu código de verificação',
    codeSent: 'Um código de 4 dígitos foi enviado para o seu telefone',
    verifyAndProceed: 'Verificar e Prosseguir',
    didntReceiveCode: 'Você não recebeu o código?',
    sendAgain: 'Enviar novamente',
    title: 'Desculpe',
    message: 'O código que você digitou está incorreto',
    code: 'Tentar novamente',
    message2Modal: 'Por favor, digite o código',
  },
  restaurants: {
    addRestaurant: 'Entre em contato para adicionar restaurante!',
  },
  suppliers: {
    addSuppliers: 'Entre em contato para adicionar fornecedores!',
  },
  menuPrimary: {
    Settings: 'Configurações',
    orders: 'Pedidos',
    records: 'Histórico',
    chat: 'Chat',
    titleSettings: 'Configurações',
  },
  stackNavigator: {
    chooseYourRestaurant: 'Escolha seu restaurante',
    suppliers: 'Fornecedores',
    makeYourOrder: 'Faça seu pedido',
    orderDetail: 'Detalhes do pedido',
  },

  productSearcher: {
    placeholder: 'Buscar produtos',
  },
  favorites: {
    findFirstPart: 'Você tem ',
    findSecondPart: ' favoritos encontrados:',
  },
  categoriesMenu: {
    favorites: 'Favoritos',
    continue: 'Continuar',
  },
  orderDetails: {
    paymentDetails: 'Detalhes de pagamento',
    net: 'Líquido',
    tax: 'Imposto',
    currentvalue: 'Valor atual',
    continue: 'Continuar',
  },
  deliveryDetail: {
    address: 'Endereço',
    deliver: 'Entrega',
    specialRequirements: 'Alguma exigência especial?',
    continue: 'Continuar',
  },
  orderSuccessful: {
    successful: 'Bem-sucedido!',
    yourOrderSuccessful: 'Seu pedido foi bem-sucedido',
    yourOrders: 'Seus pedidos',
    downloadPDF: 'Baixar PDF',
  },
  record: {
    searchPlaceholder: 'Buscar produtos',
    pastOrders: 'Pedidos antigos',
    pendingOrders: 'Pedidos pendentes',
    viewDetails: 'Ver detalhes',
    order: '#Pedido',
    amount: 'Valor',
    date: 'Data',
    noOrders: 'Ainda não há pedidos',
    bttnNoOrders: 'Faça um pedido agora',
    noOrdersDate: 'Sem pedidos nesta data',
  },
  disputeRecord: {
    enterQuantityDelivered: 'Digite a quantidade entregue:',
    addComment: 'Adicionar um comentário:',
    sendNextOrder: 'Enviar o próximo pedido',
    creditNote: 'Nota de crédito',
    wrongQuantity: 'Quantidade errada',
    defective: 'Defeituoso',
    other: 'Outro',
    leaveYourCommentsHere: 'Deixe seus comentários aqui:',
    send: 'Enviar',
  },
  uploadFile: {
    attachPhoto: 'Anexar foto:',
    customUpload: 'Upload personalizado',
  },
  pendingRecord: {
    products: 'Produtos',
    reception: 'Recepção',
    supplierDetails: 'Detalhes do fornecedor',
    productDetails: 'Detalhes do produto',
    paymentDetails: 'Detalhes do pagamento',
    tax: 'Imposto',
    currentTotal: 'Valor atual',
    checkYourProducts: 'Verifique seus produtos',
    openDispute: 'Abrir disputa',
    confirmOrder: 'Confirmar pedido',
  },
  stackRecord: {
    yourOrders: 'Seus pedidos',
    orderDetails: 'Detalhes do pedido',
    whatWentWrong: 'O que deu errado?',
  },
  settings: {
    title: 'Configurações',
    hi: 'Olá',
    helpText: 'Como podemos te ajudar?',
    restaurants: 'Restaurantes',
    editRestaurants: 'Editar seus restaurantes',
    suppliers: 'Fornecedores',
    editSuppliers: 'Editar seus fornecedores',
    languages: 'Idiomas',
    english: 'Inglês',
    spanish: 'Espanhol',
    portuguese: 'Português',
    faq: 'Perguntas frequentes',
    termsAndConditions: 'Termos e Condições',
    logOut: 'Sair',
  },
  pastRecord: {
    supplierDetails: 'Detalhes do fornecedor',
    productDetails: 'Detalhes do produto',
    paymentDetails: 'Detalhes do pagamento',
    tax: 'Imposto',
    currentTotal: 'Valor atual',
  },
  productFind: {
    youHave: 'Você tem',
    foundProducts: 'produtos encontrados:',
  },
  deleteProduct: {
    deleteProduct: 'Excluir produto',
    areYouSureToDelete: 'Tem certeza de que deseja excluir',
    cancel: 'Cancelar',
    delete: 'Excluir',
  },
  settingsFaq: {
    tittle1: 'Como o ',
    tittle2: 'podemos ajudar?',
    question1: 'Como eu adiciono outro restaurante?',
    question2: 'Como eu adiciono um fornecedor?',
    question3: 'O que é o Grownet?',
    question4: 'Onde vejo meus pedidos atuais?',
    question5: 'Um pedido recebido está incompleto. O que devo fazer?',
    answer1:
      'Entre em contato conosco através do nosso chat e informe o nome do restaurante que deseja adicionar.',
    answer2:
      'Entre em contato através do nosso chat para adicionar o fornecedor que você precisa. Lembre-se de que temos os melhores fornecedores de legumes, frutas, bebidas, carnes e muito mais.',
    answer3:
      'Descubra o Grownet: a solução de suprimentos para o seu restaurante. Facilitamos a obtenção de suprimentos, conectando-o aos principais fornecedores do mercado de Londres para obter produtos frescos e de alta qualidade a excelentes preços. Gerencie vários locais de restaurante, otimize suas compras e concentre-se no que mais importa: proporcionar uma excelente experiência gastronômica. Junte-se à revolução na gestão de suprimentos com o Grownet e eleve o seu negócio restaurante hoje!',
    answer4:
      "Acesse o menu e vá para a seção 'Registro'. Lá, você encontrará seus pedidos atuais e anteriores. Você pode filtrar por data e acessar mais detalhes sobre todos os seus produtos.",
    answer5:
      "Vá para o menu e acesse a seção 'Registro'. Procure o pedido na categoria de 'Pedidos Atuais', onde você pode filtrar por data ou fazer uma busca manual. Selecione 'Ver detalhes' e abra uma disputa para o produto que chegou incompleto.",
  },
}

export default ptTranslations
