const ptTranslations = {
  home: {
    register: 'Registrar-se',
    login: 'Entrar',
    tandc: 'Termos e condições',
  },
  login: {
    enterMobileNumber: 'Digite o número do seu celular:',
    letsBegin: 'Começar',
    phoneNumber: 'Número de telefone',
    modalTitle_1: 'Pedimos desculpas',
    FirstModalmessage: 'Não encontramos o número de celular registrado',
    FirstModalmessage2: 'Alterar número de celular',
    modalTitle_2: 'Oi 👋',
    secondModalMessage: 'Por favor, insira um número de telefone!',
  },
  codeOtp: {
    enterVerificationCode: 'Insira seu código de verificação',
    codeSent: 'Um código de 4 dígitos foi enviado para o seu telefone',
    verifyAndProceed: 'Verificar e Prosseguir',
    didntReceiveCode: 'Você não recebeu o código?',
    sendAgain: 'Enviar novamente',
  },
  restaurants: {
    addRestaurant: 'Entre em contato para adicionar restaurante!',
  },
  suppliers: {
    addSuppliers: 'Entre em contato para adicionar fornecedores!',
  },
  menuPrimary: {
    Settings: 'Configurações',
    orders: 'Pedidos',
    records: 'Histórico',
    chat: 'Chat',
    titleSettings: 'Configurações',
  },
  stackNavigator: {
    chooseYourRestaurant: 'Escolha seu restaurante',
    suppliers: 'Fornecedores',
    makeYourOrder: 'Faça seu pedido',
    orderDetail: 'Detalhes do pedido',
  },

  productSearcher: {
    placeholder: 'Buscar produtos',
  },
  favorites: {
    findFirstPart: 'Você tem ',
    findSecondPart: ' favoritos encontrados:',
  },
  categoriesMenu: {
    favorites: 'Favoritos',
    continue: 'Continuar',
  },
  orderDetails: {
    paymentDetails: 'Detalhes de pagamento',
    net: 'Líquido',
    tax: 'Imposto',
    currentvalue: 'Valor atual',
    continue: 'Continuar',
  },
  deliveryDetail: {
    address: 'Endereço',
    deliver: 'Entrega',
    specialRequirements: 'Alguma exigência especial?',
    continue: 'Continuar',
  },
  orderSuccessful: {
    successful: 'Bem-sucedido!',
    yourOrderSuccessful: 'Seu pedido foi bem-sucedido',
    yourOrders: 'Seus pedidos',
    downloadPDF: 'Baixar PDF',
  },
  record: {
    searchPlaceholder: 'Buscar produtos',
    pastOrders: 'Pedidos antigos',
    pendingOrders: 'Pedidos pendentes',
    viewDetails: 'Ver detalhes',
    order: '#Pedido',
    amount: 'Valor',
    date: 'Data',
  },
  pendingRecord: {
    products: 'Produtos',
    reception: 'Recepção',
    supplierDetails: 'Detalhes do fornecedor',
    productDetails: 'Detalhes do produto',
    paymentDetails: 'Detalhes do pagamento',
    tax: 'Imposto',
    currentTotal: 'Valor atual',
    checkYourProducts: 'Verifique seus produtos',
    openDispute: 'Abrir disputa',
    confirmOrder: 'Confirmar pedido',
  },
  stackRecord: {
    yourOrders: 'Seus pedidos',
    orderDetails: 'Detalhes do pedido',
    whatWentWrong: 'O que deu errado?',
  },
  settings: {
    title: 'Configurações',
    hi: 'Olá',
    helpText: 'Como podemos te ajudar?',
    restaurants: 'Restaurantes',
    editRestaurants: 'Editar seus restaurantes',
    suppliers: 'Fornecedores',
    editSuppliers: 'Editar seus fornecedores',
    languages: 'Idiomas',
    english: 'Inglês',
    spanish: 'Espanhol',
    portuguese: 'Português',
    faq: 'Perguntas frequentes',
    termsAndConditions: 'Termos e Condições',
    logOut: 'Sair',
  },
  pastRecord: {
    supplierDetails: 'Detalhes do fornecedor',
    productDetails: 'Detalhes do produto',
    paymentDetails: 'Detalhes do pagamento',
    tax: 'Imposto',
    currentTotal: 'Valor atual',
  },
  productFind: {
    youHave: 'Você tem',
    foundProducts: 'produtos encontrados:',
  },
  deleteProduct: {
    deleteProduct: 'Excluir produto',
    areYouSureToDelete: 'Tem certeza de que deseja excluir',
    cancel: 'Cancelar',
    delete: 'Excluir',
  },
}

export default ptTranslations
